[project]
name = "events-aggregator"
version = "0.1.0"
description = "Backend service aggregator for events"
requires-python = ">=3.9"
dependencies = [
    "fastapi",
    "uvicorn",
    "sqlalchemy",
    "asyncpg",
    "alembic",
    "httpx",
    "pydantic-settings",
    "apscheduler",
    "greenlet>=3.2.5",
    "email-validator>=2.3.0",
    "psycopg2-binary>=2.9.12",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-asyncio",
    "ruff",
]

[tool.ruff]
line-length = 88
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.pytest.ini_options]
pythonpath = ["."]
